### ISSUE TITLE
Snowflake web: Fix se_label column length in events_staged

### ISSUE THREAD

**Issue by adatzer** [snowplow/data-models#109]
At the moment, the Snowflake web model sets `se_label` column length to 1000: https://github.com/snowplow/data-models/blob/9bf46f3d08d0305ee23ac8146dfdf3468c5619ec/web/v1/snowflake/sql-runner/sql/standard/01-base/01-main/00-setup-base.sql#L176 (related to https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/134).

This prevents the commit step of base module to succeed when the `se_label` column is of 4096 length in `atomic.events`, which is now normally the case.

**Comment by colmsnowplow** [comment]
Note that even if we're dealing with an `atomic.events` table which has it set to 1000, 4096 in the model won't break.
