### ISSUE TITLE
scratch.events_staged definition is static, scratch.events_this_run mutates with atomic.events

### ISSUE THREAD

**Issue by aidanradford** [snowplow/data-models#111]
scratch.events_staged has a written out DDL statemenhttps://github.com/snowplow/data-models/blob/master/web/v1/snowflake/sql-runner/sql/standard/01-base/01-main/00-setup-base.sql#L106

scratch.events_this_run is a table that can mutate along with the structure of atomic.events every time the procedure is run:
https://github.com/snowplow/data-models/blob/master/web/v1/snowflake/sql-runner/sql/standard/01-base/01-main/06-events-this-run.sql#L18

This mismatch between events_staged and events_this_run will lead to failure of the derived.commit_staged procedure:
https://github.com/snowplow/data-models/blob/master/web/v1/snowflake/sql-runner/sql/standard/01-base/01-main/09-commit-base.sql#L21
If:
- a user has enabled any automatic enrichements (any UA parser)
- a user has enabled performance timing
- a user has enabled the spiders and robots enrichment
- a user is tracking custom events or entities

Proposed solution:

Replace https://github.com/snowplow/data-models/blob/master/web/v1/snowflake/sql-runner/sql/standard/01-base/01-main/00-setup-base.sql#L106-L268

With:

```
-- Create staged table

CREATE OR REPLACE PROCEDURE {{.scratch_schema}}.create_events_staged()
  RETURNS VARCHAR
  LANGUAGE JAVASCRIPT
  AS
  $$

  var sql_stmt = `
      SELECT listagg(isc.column_name, ',') WITHIN GROUP (order by isc.ordinal_position)
      FROM information_schema.columns AS isc
      WHERE table_schema=UPPER('{{.input_schema}}')
        AND table_name=UPPER('events')
        AND column_name != UPPER('contexts_com_snowplowanalytics_snowplow_web_page_1');`;

  var res = snowflake.createStatement({sqlText: sql_stmt}).execute();
  res.next();
  var result = res.getColumnValue(1);

  var new_col = 'contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id::varchar(36) AS page_view_id';
  if (result !== '') {
      new_col = new_col + ',';
  }

  var fin_query=`
    CREATE OR REPLACE TABLE {{.scratch_schema}}.events_staged{{.entropy}}
    AS
      SELECT
        ` + new_col + ` ` + result + `
      FROM {{.input_schema}}.events AS a
      WHERE 1=0 ;`;

  snowflake.createStatement({sqlText: fin_query}).execute();

  return 'ok. create_events_staged succeeded.';

  $$
;

CALL {{.scratch_schema}}.create_events_staged();
```

**Comment by bill-warner** [comment]
Hi Aidan thanks for raising this.

Do you have a specific example of this kind of failure? The reason I ask is that the `derived.commit_staged` procedure you mention should alter the `events_staged` table to match the `events_this_run` table as part of the upsert step:

https://github.com/snowplow/data-models/blob/9bf46f3d08d0305ee23ac8146dfdf3468c5619ec/web/v1/snowflake/sql-runner/sql/standard/00-setup/01-main/01-stored-procedures.sql#L185-L193

This mutation will fail however the newly added columns to `events_this_run` occur anywhere but the far right hand side of the table, since you can only add columns to the RHS of the `events_staged` table. I can't readily think of a situation where this should occur, however perhaps you have stumbled upon one.

**Comment by aidanradford** [comment]
The issue described here is actually related to the following issue:
https://github.com/snowplow/data-models/issues/109

The error message received is:

```
* Query 09-commit-base /tmp/datamodeling_work_dir/com_{{acme}}/pipeline/datamodeling/webmodel/sql-runner/sql/standard/01-base/01-main/09-commit-base.sql (in step 09-commit-base @ target com.{{acme}}-prod1 Snowflake), ERROR:
  - 100132 (P0000): JavaScript execution error: Uncaught Execution of multiple statements failed on statement "CALL derived.commit_staged(
  ..." (at line 1, position 0).
Execution error in store procedure COMMIT_STAGED:
JavaScript execution error: Uncaught ERROR: Source table is missing column(s) which exist in target table. in COLUMN_CHECK at '      throw "ERROR: Source table is missing column(s) which exist in target table.";' position 6
stackstrace: 
COLUMN_CHECK line: 9
At Statement.execute, line 13 position 55 in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
stackstrace: 
SYSTEM$MULTISTMT line: 10

```

I would ascribe the root cause for both issues to the mismatch described in the original message.

**Comment by aidanradford** [comment]
Closing this issue as the `commit_table` function manages any additional columns outside of the normal static columns. 
Fixing the se_label column definition is sufficient.
