### ISSUE TITLE
Add stored procedures to more automatically generate custom event-level tables

### ISSUE THREAD

**Issue by jensnowplow** [snowplow/data-models#114]
If a Snowplow user wants to easily generate and load onto a table with custom Snowplow events, is there a way to create a stored procedure where you identify the types of events to include (e.g. from `event_name`) and the name of columns (including custom contexts), and a procedure similar to [this commit one](https://github.com/snowplow/data-models/blob/master/web/v1/bigquery/sql-runner/sql/custom/02-custom-example/03-commit.sql) can create the table from `events_staged` without the intermediate steps?

Example:
I have created a `ui_interaction` event for which I am generating the majority of my data. I want an easy way to create a custom `derived.ui_interactions` table by specifying the type of event that goes into the table, and the columns that I want in the table.

```
event_table_name: 'ui_interactions',
event_name: 'ui_interaction',
columns: [ 'start_tstamp', 'page_view_id', 'x', 'y', 'z']
```

**Comment by colmsnowplow** [comment]
commit_table commits rows from a staging table to a derived table, (using `DELETE FROM... INSERT INTO` IIRC).

So to achieve what you want you do this (in whatever syntax you're after, and with whatever values your table needs):

```
CREATE OR REPLACE TABLE scratch.ui_interactions AS(
SELECT 'start_tstamp', 'page_view_id', 'x', 'y', 'z' FROM events_staged WHERE event_name = 'ui_interaction')


CALL {{.output_schema}}.commit_table('scratch',                   -- sourceDataset
                                     'ui_interactions', -- sourceTable
                                     'derived',                    -- targetDataset
                                     'ui_interactions',        -- targetTable
                                     'event_id',                          -- joinKey
                                     'collector_tstamp',                          -- partitionKey
                                     TRUE);                                   -- automigrate
```

I think I get why one might want a stored procedure to do both steps but IMO it wouldn't really save any work it would just obscure the logic with v little payoff.

**Comment by jensnowplow** [comment]
@colmsnowplow That's a really good point!

**Comment by colmsnowplow** [comment]
@jensnowplow I just realised, if it's redshift and the data is in a different table, it's slightly more complicated, in that you need a join like this one: https://github.com/snowplow/data-models/blob/9bf46f3d08d0305ee23ac8146dfdf3468c5619ec/web/v1/redshift/sql-runner/sql/custom/02-page-views-join/02-page-views-join-staged.sql#L24-L31 

I do think it's worth thinking about how to avoid that part of the process alright, but at least for now it's the same process once you've joined to the staged table. :)
