### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/data-models#127]
In the dbt section of the readme:

> For users using dbt we have the [snowplow-web](https://github.com/snowplow/dbt-snowplow-web)[](https://github.com/snowplow/data-models#using-other-tools) dbt package, allowing you to run the web model via dbt. Currently the package only supports Redshift, with BigQuery and Snowflake support to follow soon. Similarly, the mobile model will soon be supported in dbt.

^^ This is out of date, I believe we support all of those things now.

**Comment by bill-warner** [comment]
Good spot
