### ISSUE TITLE
Redshift: Update test on page_view_in_session_index

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/data-models#13]
The BQ v1 release will introduce a different way of testing page_view_in_session_index, which adds testing for new edge cases. Update Redshift version to use the same (and remove existing test).

**Comment by colmsnowplow** [comment]
Readmes should also be updated to suit new test scripts once BQ v1 is released.

**Comment by bill-warner** [comment]
Sorry which README. Struggling to find the reference

**Comment by colmsnowplow** [comment]
Errr - I'm not sure I've added this comment to the right issue. 

Bear with me I'll look back at it and clarify. My bad!
