### ISSUE TITLE
Snowflake Web: Optimise partition pruning

### ISSUE THREAD

**Issue by agnes-kiss** [snowplow/data-models#140]
Two of the scratch tables that select from the `events` table use a subquery to filter the data on the query limits. This may cause issues for partition pruning in Snowflake as described in [this](https://community.snowflake.com/s/article/Pruning-is-not-happening-subquery) article. 

Affected tables:

```
{{.scratch_schema}}.base_sessions_to_process{{.entropy}}
{{.scratch_schema}}.events_this_run{{.entropy}}
```

To improve partition pruning the subquery needs to be replaced with alternative SQL methods (e.g.: by abstracting them to variables during a stored procedure)

**Comment by colmsnowplow** [comment]
Wow good catch agnes. 🕵️‍♀️  We ran into a similar problem in BigQuery dating way back to the v0 models - and indeed we resolved it with your suggested approach of using variables if memory serves.

**Comment by agnes-kiss** [comment]
It has actually been highlighted to us by Anthony Gianastasio at Digital Virgo, so shoutout to him. Since then I tested it locally and it seems indeed this could have a big impact.

**Comment by agianastasio** [comment]
Hello Snowplow team!
Thanks for the shoutout ;) And even more for your reactivity!! it's greatly appreciated.

**Comment by agianastasio** [comment]
Hello Snowplow,

We've just tested the change and the impact is tremendous ! Game Changer!

![image](https://user-images.githubusercontent.com/73526430/196738280-0653f864-7aaa-4854-b31c-6dd14384b17d.png)

In Snowflake, checking query plans, we went from Full table scan to a scan of less than 1% of the partitions!

**Comment by agnes-kiss** [comment]
Amazing, very happy it worked as planned! ;)
