### ISSUE TITLE
BigQuery: Handle schema evolution in core contexts

### ISSUE THREAD

**Issue by aidanradford** [snowplow/data-models#52]
All newly implemented customers only have data for yauaa version 1-0-1

https://github.com/snowplow/data-models/blob/master/web/v1/bigquery/sql-runner/sql/standard/02-page-views/01-main/01-
page-view-events.sql#L131

A coalesce w/ version 1-0-0 might be useful for backwards compatibility - but not sure if this would break anything downstream.

**Comment by colmsnowplow** [comment]
This should be a coalesce of the two, but taking into account that 1-0-0 might not exist for some customers.

We should consider if this is best solved using a generic procedure to coalesce versioned columns in BQ - which would also solve the last major pain point of working with BQ data.
