### ISSUE TITLE
Update images for accessibility

### ISSUE THREAD

**Issue by pwm1991** [snowplow/data-models#69]
As a colour blind user I have a hard time reading the diagrams, particularly the red boxes. I have to zoom in so the box fills most of the screen in order to read the text. Can the text be updated so it has a higher contrast (e.g. white text?) 

Thanks!

**Comment by colmsnowplow** [comment]
Thanks for flagging @pwm1991.

Is the colourscheme in the attached image better? (I have run it through a tool to check also)

I've tried to pick better colours and lighten them. Please don't be shy in pointing out if any part of it is still unclear, more than happy to tweak this. :)

![dm_new_colours](https://user-images.githubusercontent.com/25744626/112838265-c9322b80-9094-11eb-9267-fd785c00a4a3.jpg)

**Comment by pwm1991** [comment]
@colmsnowplow thanks for actioning so quickly :) Yes that's amazing. Thanks!

**Comment by colmsnowplow** [comment]
Not a problem, thank you for pointing it out! It's funny, I think I didn't notice how unclear the red was as I'm moderately red/green colourblind myself. So used to straining to see certain things that I didn't notice it 😄 .
