### ISSUE TITLE
Deduplication data model: fix typo in SQL script

### ISSUE THREAD

**Issue by dilyand** [snowplow/data-models#87]
I think this line should be commented out by default and only uncommented by users after the initial run of the script: https://github.com/snowplow/snowplow/blob/master/5-data-modeling/deduplication-queries/sql/02-events-without-fingerprint.sql#L143

**Comment by colmsnowplow** [comment]
Closing as not relevant to this repo. Looking to figure out proper channel for snowplow/snowplow issue as I think this refers to something we should just deprecate.
