### ISSUE TITLE
Documentation loop

### ISSUE THREAD

**Issue by Thijxx** [snowplow/data-models#9]
In the documentation you refer to data  `Documentation for the data models can be found on our documentation site.` and this link send me to a website where there is a link sending me back to the readme. Documentation Inception :D

**Comment by colmsnowplow** [comment]
Hey we're engineers, we like feedback loops. :D 

But to be serious - do you mean the link in the [Repo Contents](https://github.com/snowplow/data-models#repo-contents) section of the front readme?

**Comment by colmsnowplow** [comment]
PS. apologies for the late response - not sure how I missed it!

**Comment by Thijxx** [comment]
> Hey we're engineers, we like feedback loops. :D
> 
> But to be serious - do you mean the link in the [Repo Contents](https://github.com/snowplow/data-models#repo-contents) section of the front readme?

Yes. Then in the section `The Snowplow web data model` there is the link in `The Snowplow web data model v1.0.0 can be found in the snowplow/data-models GitHub repository. ` So I still don't understand the data model :)

**Comment by colmsnowplow** [comment]
Right - so in this repo we link to the documentation. In the documentation we link to the repo. If you need docs, you can find them in the documentation site. If you need source code you can find them in this repo. I'm not sure I understand what's problematic about linking from one to the other and vice-versa?

**Comment by colmsnowplow** [comment]
Wait perhaps I've missed the point - is it that the documentation basically presents the same information as the readme? And perhaps that this isn't the information you were expecting?

If so, then we should have a look at that - it would be useful to know what information you're expecting to see/what is missing which might help you understand.

**Comment by Thijxx** [comment]
I was wondering what are the fields (entities?) mean that come from the SP JS tracker, for example the page_view Events. So I thought that there must be some kind of overview of the default fields and how they fit together in a model.

I start reading in the Git README, I read there that the "documentation for the data models can be found on our documentation site". I go there, then I see the link "The Snowplow web data model" so I go there. 

Then I read these three sentences and I'm lost, is it down below, deprecated or on Git where I just came from.

- More information on the model structure and customization options can be found below.
- The Snowplow web data model v1.0.0 can be found in the snowplow/data-models GitHub repository. 
- Please note that snowplow/snowplow-web-data-model has been deprecated.

I left the site and used Google to come back to the site and then on this page: https://docs.snowplowanalytics.com/docs/understanding-your-pipeline/canonical-event/ and that is what I was looking for I think so feel free to close this issue :)

**Comment by colmsnowplow** [comment]
Ah I see where you're coming from. It's a fair point - there's a lot of documentation scattered around and it's not necessarily easy to follow. We have an ongoing effort to improve this generally and establish the docs site as a single source of truth. 

Thanks for pointing this out - we'll try to improve things further on this front.

**Comment by colmsnowplow** [comment]
Hey @Thijxx  - it just occurred to me that what
