### ISSUE TITLE
Bigquery Mobile: App Errors not an optional module by default

### ISSUE THREAD

**Issue by aidanradford** [snowplow/data-models#91]
In the sessions table app error fields are expected values, if the optional app errors module is not enabled then these fields have to be removed. I suggest we remove these fields by wrapping them in some conditional Go, and adding a 'app_errors' boolean to the sessions playbook? Something like:

{{if eq .app_errors true}}

columns

{{end}}

Although this solution does not deal with how to handle app_error events being implemented after the datamodel has been running for a period of time. From a client's perspective I feel like there are 2 possible solutions?

1. Append the 'app_error' fields to the tables manually (it looks like [there is not a way to do this using sql-runner](https://cloud.google.com/bigquery/docs/managing-table-schemas#adding_a_column_in_a_load_append_job)??)
2. Create separate tables for optional modules as datamodel 'plug-ins?' 

The following areas needed editing to get the model live without app errors enabled:

Sessions Links:
- [04-sessions/01-main/00-setup-sessions](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/04-sessions/01-main/00-setup-sessions.sql#L111-L112)
- [04-sessions/01-main/01-sessions-aggs part 1](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/04-sessions/01-main/01-sessions-aggs.sql#L54-L64)
- [04-sessions/01-main/01-sessions-aggs part 2](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/04-sessions/01-main/01-sessions-aggs.sql#L76-L83)
- [04-sessions/01-main/03-sessions](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/04-sessions/01-main/03-sessions.sql#L42-L43)
- [04-sessions/99-complete/98-truncate-upstream-staged](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/04-sessions/99-complete/98-truncate-upstream-staged.sql#L19)

Users Links:
- [05-users/01-main/00-setup-users](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/05-users/01-main/00-setup-users.sql#L115-L116)
- [05-users/01-main/04-users-aggs](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/05-users/01-main/04-users-aggs.sql#L31-L32)
- [05-users/01-main/06-users](https://github.com/snowplow/data-models/blob/master/mobile/v1/bigquery/sql-runner/sql/standard/05-users/01-main/06-users.sql#L38-L39)

**Comment by colmsnowplow** [comment]
App errors is optional. Please [read the readme](https://github.com/snowplow/data-models/tree/master/mobile/v1/bigquery/sql-runner/playbooks/standard/03-optional-modules/01-app-errors).
